# Sample server and autodiscovery rules.
# Format:
# MailDomainInclude=domain|Type=IMAP|Server=imap.example.com|Port=993|Encryption=SSL
# MailDomainInclude=domain|Type=POP3|Server=pop.example.com|Port=995|Encryption=SSL
# MailDomainInclude=domain|Type=Exchange|Url=https://autodiscover.example.com/EWS/Exchange.asmx

MailDomainInclude=gmail.com|Type=IMAP|Server=imap.gmail.com|Port=993|Encryption=SSL
MailDomainInclude=gmail.com|Type=POP3|Server=pop.gmail.com|Port=995|Encryption=SSL
MailDomainInclude=outlook.com|Type=IMAP|Server=imap-mail.outlook.com|Port=993|Encryption=SSL
MailDomainInclude=outlook.com|Type=POP3|Server=pop-mail.outlook.com|Port=995|Encryption=SSL
MailDomainInclude=hotmail.com|Type=IMAP|Server=imap-mail.outlook.com|Port=993|Encryption=SSL
MailDomainInclude=hotmail.com|Type=POP3|Server=pop-mail.outlook.com|Port=995|Encryption=SSL
MailDomainInclude=yahoo.com|Type=IMAP|Server=imap.mail.yahoo.com|Port=993|Encryption=SSL
MailDomainInclude=yahoo.com|Type=POP3|Server=pop.mail.yahoo.com|Port=995|Encryption=SSL
MailDomainInclude=zoho.com|Type=IMAP|Server=imap.zoho.com|Port=993|Encryption=SSL
MailDomainInclude=zoho.com|Type=POP3|Server=pop.zoho.com|Port=995|Encryption=SSL
MailDomainInclude=outlook.com|Type=Exchange|Url=https://autodiscover.outlook.com/EWS/Exchange.asmx
MailDomainInclude=office365.com|Type=Exchange|Url=https://autodiscover.outlook.com/EWS/Exchange.asmx
